repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: no-commit-to-branch
        args: [--branch, main]

  - repo: https://github.com/sensiblebit/.github
    rev: 4e98a46c1fed27308583c0a86ee955739a137e36
    hooks:
      - id: branch-name
      - id: commit-message
        stages: [commit-msg]
      - id: goimports
      - id: go-vet
      - id: go-build
      - id: go-test

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.47.0
    hooks:
      - id: markdownlint
